# --- ETAPA 1: Compilación en la nube ---
FROM maven:3.9.6-eclipse-temurin-21-alpine AS build

# Docker crea su carpeta virtual en la nube
WORKDIR /app

# Copiamos
COPY . .

# Entramos en la carpeta donde realmente tienes el código
WORKDIR /app/back

# Ahora sí, Maven encontrará el pom.xml padre y compilará solo el servicio de usuarios
RUN MAVEN_OPTS="-Xmx256m" mvn clean package -pl usuarios-service -am -DskipTests

# --- ETAPA 2: Ejecución ---
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app

# OJO A LA RUTA: Rescatamos el .jar desde la carpeta back
COPY --from=build /app/back/usuarios-service/target/usuarios-service-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8081
ENTRYPOINT ["java", "-jar", "app.jar"]