# --- ETAPA 1: Compilación en la nube ---
FROM maven:3.9.6-eclipse-temurin-21-alpine AS build
WORKDIR /app
COPY . .

# Entramos en tu carpeta de código
WORKDIR /app/back

# Compilamos solo el gateway
RUN MAVEN_OPTS="-Xmx256m" mvn clean package -pl api-gateway -am -DskipTests

# --- ETAPA 2: Ejecución ---
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app

# Rescatamos el .jar desde la carpeta back
COPY --from=build /app/back/incidencias-service/target/incidencias-service-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]