# --- ETAPA 1: Compilación en la nube ---
FROM maven:3.9.6-eclipse-temurin-21-alpine AS build
WORKDIR /app
COPY . .

# 1. EL TRUCO DE MAVEN: Ponemos los ":" delante de usuarios-service
RUN MAVEN_OPTS="-Xmx256m" mvn clean package -pl :usuarios-service -am -DskipTests

# --- ETAPA 2: Ejecución ---
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app

# 2. AJUSTE DEL COPY: Al estar el código en la raíz, el target se genera en /app/target/
COPY --from=build /app/target/usuarios-service-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8081
ENTRYPOINT ["java", "-jar", "app.jar"]