version: '3.8'

services:
  incidencias-service-tfg:
    build: ./incidencias-service
    container_name: proyecto-incidencias
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server-tfg
    networks:
      - red-tfg

  usuarios-service-tfg:
    build: ./usuarios-service
    container_name: proyecto-usuarios
    ports:
      - "8081:8081"
    depends_on:
      - incidencias-service-tfg
      - eureka-server-tfg
    networks:
      - red-tfg

  api-gateway-tfg:
    build: ./api-gateway
    container_name: proyecto-gateway
    ports:
      - "8080:8080"
    depends_on:
      - usuarios-service-tfg
      - incidencias-service-tfg
      - eureka-server-tfg
    networks:
      - red-tfg

  eureka-server-tfg:
    build: ./eureka-server
    container_name: eureka-server-tfg
    ports:
      - "8761:8761"
    networks:
      - red-tfg
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  red-tfg:
      driver: bridge